### ISSUE TITLE
从缓存读取链接时获取失败

### ISSUE THREAD

**Issue by cntvc** [cntvc/Genshin-Impact-Tools#34]
### 系统版本 (System Version)

Windows10 or Windows11

### 软件版本 (Software version)

0.1.5

### 发生了什么？ (What happened?)

在抽卡历史记录页面，翻页后查看活动祈愿详情介绍页（介绍概率的页面），再导出数据时报错

预计发生：
正常查询抽卡数据然后生成报告

### 相关日志输出 (Relevant log output)
```txt
2023-01-24 22:02:38 | DEBUG | gacha_url.py:102 | get_url() | message:   从游戏缓存获取抽卡链接
2023-01-24 22:02:38 | DEBUG | gacha_url.py:110 | get_url() | message:   开始读取缓存
2023-01-24 22:02:38 | DEBUG | gacha_url.py:115 | get_url() | message:   删除临时文件C:\Users\cntvc\AppData\Local\Temp\tmp6o95j3u3
2023-01-24 22:02:38 | DEBUG | gacha_url.py:33 | verify_url() | message:   验证链接有效性
2023-01-24 22:02:38 | DEBUG | gacha_url.py:34 | verify_url() | message:   https://webstatic.mihoyo.com/hk4e/event/e20190909gacha-v2/index.html?win_mode=fullscreen&authkey_ver=1&sign_type=2&auth_appid=webview_gacha&gacha_id=6bb70a968c3ff75e0ead26ae707aa3c726053aa2&timestamp=1673997794&lang=zh-cn&device_type=pc&game_version=CNRELWin3.4.0_R12707997_S12671397_D12787608&plat_type=pc&region=cn_gf01&authkey=4XMHK4vpuxVIV9nTi862UJNzLxTk8MgmsydB5PD0uS3%2f0AbOOLI6n2BME44qMyWtjAT%2bNRZhbNTU%2fxZhpEQDVo34HLQC%2bIOlzRwH4XMLBhLubrTNTxi5wEHtXMWyO0hLabKklOcO0t1ezelOVo%2fxQet85qJHsZkvBAOoNdHyeW9g80bIynTPsXjRKIPLhbXV3J%2bU6OfEHxMBZEZOO9UbOHoCHNG0tzg1Ylpfd5%2bOXbFKFkvebFB3yNkd2IL71uNqci%2b%2fFbo6nxZzQRKFlhnH4%2fQMJ4q1xyP16DpPf00B3d4NQnm15EbUEAkdoB5uRwNByOx88rqatks0qUPmJPIu3wMGz4nS2RoQpTFwtewXVEfELbJgjgoNnfgqB%2bN3O9boOwJkN4SOC1ycpaYQJKRaXhDn95ciHVOE1gks%2f1olmMrzpSU7Yml9wkfuotmBHIa9%2fRY0oMkdVT84ZfGR%2bUfQpojXHmI%2bz3vfraCB1IRxMQ37VuU0svrj5H1WTMGb5U65WeeyuSbbgs%2fYK5S6lh3pusiZf%2flry6b5ODiWtu4RL5iitu4D6XDAHNgrwJVcpORuobhiZiO9aLZL74TvukaF%2b3jYOsItFYlnFj1ZuMf%2fQlmWaD7OOdV8I4AZ6Yowqn3q0A5qT621I1tr%2boz07vPj7MvtTGPRbiHDKLhyW6yLS4XuFqk1p7N%2fi6%2fHz9%2fJODKRkLPSsToP0in2ADLXDy6GSPfU7Z8WHrrLBLarim0NyYLoFI2CtDlz8rigEXdpnSpJGvG7hLpWTnRBMdDrXEutyDZvz7YUjImH%2bLC8Zhx%2f4kfgzyWqtxxrlYCwvsShQcQEWq%2bKHOa4zePWruzV2VDwpPd4vGpF7JmmevRXuTKiCfBJ7%2bMMrWj42ax9i0qGSsVVsusXseh3WaQdmCN7opLPcG9paw%2b%2f0BOEt9nm6MavJXk4%2f2MPc6iexcANgtMP6pavqAp8PLnrfrXwZHRLroTr1zynRc7Y4Zj4HcCbfXGMChErVOvxBpfzRLrNa9H2H0ewRQ88p0qYh%2bG5vsrW%2f7GA6IIkVGZ55b%2bCPk2mqngwazUMFbUMIuFUCegR7MJ%2fsLoOGfROL3WHzuZY2%2fEzvs7LQebGdPJVoHwAN5VESVJIAIkUONWvp0OgH8s%2fnMJFDdrdLJhFtPa8UKdvlVOblOXDf5vu6rpBxykI6MeAw%2fSuboOxR4IqnNsZS2qMLLuSWND9YroNzNn70laHUeuiMc08vn%2bEDYLAxihXSatOCuduD0pHU8RADC2MYPyzh8O2iLC9ZmjFt820MSQCxFC4%2fP6CUY8Dv5Z23%2fJ%2fmfPuj%2f%2fN%2bHDNKdvhKi1s959SZoDChZm0Fip4ZOoDZ5h32K4gyXLmgw%3d%3d&game_biz=hk4e_cn
2023-01-24 22:02:38 | ERROR | main.py:104 | <module>() | message:   An error has been caught in function '<module>', process 'MainProcess' (19284), thread 'MainThread' (20808):
Traceback (most recent call last):

> File "d:/Github/Genshin/Genshin-Impact-Tools/src/genshin/main.py", line 104, in <module>
    run()
    └ <function run at 0x00000281014C0D38>

  File "d:/Github/Genshin/Genshin-Impact-Tools/src/genshin/main.py", line 100, in run
    menu.run()
    │    └ <function Menu.run at 0x00000281014C6678>
    └ <genshin.module.menu.Menu object at 0x0000028100589888>

  File "D:\Github\Genshin\Genshin-Impact-Tools\src\genshin\module\menu.py", line 71, in run
    self.run()
    │    └ <function Menu.run at 0x00000281014C6678>
    └ <genshin.module.menu.Menu object at 0x0000028100589888>

  File "D:\Github\Genshin\Genshin-Impact-Tools\src\genshin\module\menu.py", line 73, in run
    option()
    └ <function <lambda> at 0x000002817D683558>

  File "d:/Github/Genshin/Genshin-Impact-Tools/src/genshin/main.py", line 19, in <lambda>
    "options": lambda: export(settings.URL_SOURCE_GAMECACHE),
                       │      └ <dynaconf.base.LazySettings object at 0x000002817D8A5988>
                       └ <function export at 0x0000028100580AF8>

  File "D:\Github\Genshin\Genshin-Impact-Tools\src\genshin\module\gacha\__init__.py", line 31, in export
    if not user.get_gacha_url() or not verify_url(user.get_gacha_url()):
           │    │                      │          │    └ <function User.get_gacha_url at 0x00000281014BB3A8>
           │    │                      │          └ <genshin.module.user.User object at 0x00000281014B91C8>
           │    │                      └ <function verify_url at 0x00000281014B6D38>
           │    └ <function User.get_gacha_url at 0x00000281014BB3A8>
           └ <genshin.module.user.User object at 0x00000281014B91C8>

  File "D:\Github\Genshin\Genshin-Impact-Tools\src\genshin\module\gacha\gacha_url.py", line 39, in verify_url
    res_json = json.loads(res)
               │    │     └ '<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n  <meta charset="UTF-8">\n  <!-- HTTP 1.1 -->\n  <meta...
               │    └ <function loads at 0x000002817D995D38>
               └ <module 'json' from 'c:\\users\\cntvc\\appdata\\local\\programs\\python\\python37\\lib\\json\\__init__.py'>

  File "c:\users\cntvc\appdata\local\programs\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
           │                │      └ '<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n  <meta charset="UTF-8">\n  <!-- HTTP 1.1 -->\n  <meta...
           │                └ <function JSONDecoder.decode at 0x000002817D995048>
           └ <json.decoder.JSONDecoder object at 0x000002817D985388>

  File "c:\users\cntvc\appdata\local\programs\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ '<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n  <meta charset="UTF-8">\n  <!-- HTTP 1.1 -->\n  <meta...
               │    │          │      └ <built-in method match of re.Pattern object at 0x000002817D926CF0>
               │    │          └ '<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n  <meta charset="UTF-8">\n  <!-- HTTP 1.1 -->\n  <meta...
               │    └ <function JSONDecoder.raw_decode at 0x000002817D9950D8>
               └ <json.decoder.JSONDecoder object at 0x000002817D985388>

  File "c:\users\cntvc\appdata\local\programs\python\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ '<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n  <meta charset="UTF-8">\n  <!-- HTTP 1.1 -->\n  <meta...
          └ <class 'json.decoder.JSONDecodeError'>
```

**Comment by cntvc** [comment]
由于从缓存取抽卡链接时直接取最后一个符合正则的链接，而详情页的网页链接也匹配该正则，请求该网页返回的数据并非json格式，最终导致Json解析错误。

**Comment by cntvc** [comment]
相关提交
https://github.com/sunfkny/genshin-gacha-export/commit/0c7913bc9f3b731f6b892a52db7cf211e1bf4926
